name: Despliegue Final Leslie

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flask
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_11560183153F43E090E05537B4CCE19A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_68EFC273DC7D40F3A3B004C6C090B2FB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D993DE5320F247C595938424D2B55EE7 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tarea-azure-final-leslie' # Asegúrate que este sea el nombre real en el Portal de Azure